/**
 * AuditTabs — tab bar for the chat-audit shell.
 *
 * Thin adapter: declares the 4 DevAudit tabs and delegates all ARIA tablist
 * behaviour, keyboard navigation, and styling to the generic TabShell.
 * The tab IDs/controls it emits (`audit-tab-{key}` / `audit-panel-{key}`)
 * are generated by TabShell using testIdPrefix="audit-tab", preserving
 * backwards compatibility with any existing aria-labelledby anchors in
 * dev-audit-shell.tsx.
 */
import React from 'react';
import { TabShell, resolveTab } from '../../shell/tab-shell';
import type { TabDef } from '../../shell/tab-shell';

// ---------------------------------------------------------------------------
// Tab definitions — specific to chat-audit; owned here, not in the shell.
// ---------------------------------------------------------------------------

const AUDIT_TABS: TabDef[] = [
  { key: 'sessions',    label: 'Sessions',    path: '/dev/chat-audit/sessions' },
  { key: 'search',      label: 'Search',      path: '/dev/chat-audit/search' },
  { key: 'leaderboard', label: 'Leaderboard', path: '/dev/chat-audit/leaderboard' },
  { key: 'cache',       label: 'Cache',       path: '/dev/chat-audit/cache' },
];

// Re-export so any caller that previously imported resolveAuditTab can
// migrate gradually. New callers should use resolveTab directly.
export function resolveAuditTab(pathname: string): string {
  return resolveTab(pathname, AUDIT_TABS);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface AuditTabsProps {
  /** Optional testid prefix forwarded to TabShell (default 'audit-tab'). */
  testIdPrefix?: string;
}

export function AuditTabs({ testIdPrefix = 'audit-tab' }: AuditTabsProps) {
  return (
    <TabShell
      basePath="/dev/chat-audit"
      tabs={AUDIT_TABS}
      ariaLabel="Chat Audit"
      testIdPrefix={testIdPrefix}
    />
  );
}
