/**
 * AuditTabs — tab bar for the chat-audit shell.
 *
 * Thin adapter: declares the 4 DevAudit tabs and delegates all ARIA tablist
 * behaviour, keyboard navigation, and styling to the generic TabShell.
 * The tab IDs/controls it emits (`audit-tab-{key}` / `audit-panel-{key}`)
 * are generated by TabShell using testIdPrefix="audit-tab", preserving
 * backwards compatibility with any existing aria-labelledby anchors in
 * dev-audit-shell.tsx.
 */
import React from 'react';
import { TabShell, resolveTab } from '../../shell/tab-shell';
import type { TabDef } from '../../shell/tab-shell';

// ---------------------------------------------------------------------------
// Tab definitions — specific to chat-audit; owned here, not in the shell.
// Built from a base path so the same tab set works at /dev/chat-audit and
// /admin/dev/chat-audit. Starters is opt-out (admin hub drops it — it's a
// global dev QA viewer, not a cross-user audit concern).
// ---------------------------------------------------------------------------

export function buildAuditTabs(
  basePath: string,
  { includeStarters = true }: { includeStarters?: boolean } = {},
): TabDef[] {
  const tabs: TabDef[] = [
    { key: 'sessions',    label: 'Sessions',    path: `${basePath}/sessions` },
    { key: 'search',      label: 'Search',      path: `${basePath}/search` },
    { key: 'leaderboard', label: 'Leaderboard', path: `${basePath}/leaderboard` },
    { key: 'cache',       label: 'Cache',       path: `${basePath}/cache` },
  ];
  if (includeStarters) {
    tabs.push({ key: 'starters', label: 'Starters', path: `${basePath}/starters` });
  }
  return tabs;
}

// Re-export so any caller that previously imported resolveAuditTab can
// migrate gradually. New callers should use resolveTab directly.
export function resolveAuditTab(pathname: string): string {
  return resolveTab(pathname, buildAuditTabs('/dev/chat-audit'));
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface AuditTabsProps {
  /** Base path the shell is mounted at (default standalone /dev/chat-audit). */
  basePath?: string;
  /** Explicit tab set; defaults to the full set built from basePath. */
  tabs?: TabDef[];
  /** Optional testid prefix forwarded to TabShell (default 'audit-tab'). */
  testIdPrefix?: string;
}

export function AuditTabs({
  basePath = '/dev/chat-audit',
  tabs,
  testIdPrefix = 'audit-tab',
}: AuditTabsProps) {
  return (
    <TabShell
      basePath={basePath}
      tabs={tabs ?? buildAuditTabs(basePath)}
      ariaLabel="Chat Audit"
      testIdPrefix={testIdPrefix}
    />
  );
}
