#!/usr/bin/env bash
# Generate the multi-tenant table/column inventory + freshness for the cube port.
# Writes reports/multi-tenant-table-inventory.md. Read-only Trino.
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
PY="$HOME/.claude/skills/.venv/bin/python3"
Q="$PY $HERE/trino_q.py"
OUT="$HERE/../reports/multi-tenant-table-inventory.md"
mkdir -p "$HERE/../reports"

# Tables backing the ported cubes, per tenant.
SHARED="mf_users mf_ingame_roles map_ingame_devices_and_userid map_ingame_ips_and_userid std_ingame_user_active_daily std_ingame_user_recharge_daily std_ingame_user_active_monthly std_ingame_user_recharge_monthly etl_ingame_recharge etl_ingame_login etl_ingame_logout etl_ingame_register cons_game_key_metrics_daily cons_game_new_user_retention_daily std_marketing_cost_all_channels_by_game"
CFM_EXTRA="etl_ingame_game_detail etl_ingame_moneyflow etl_ingame_lotteryshoot etl_ingame_newbiedetail etl_ingame_newbietutorial etl_ingame_propflow etl_ingame_roommatchflow etl_ingame_teamstartmatchflow"

{
  echo "# Multi-Tenant Table Inventory (live Trino: game_integration)"
  echo "_Generated by build_inventory.sh — read-only. cfm/cros/tf. vga deferred._"
  echo
  for SCHEMA in cfm_vn cros tf; do
    echo "## $SCHEMA"
    TABLES="$SHARED"
    [ "$SCHEMA" = "cfm_vn" ] && TABLES="$SHARED $CFM_EXTRA"
    for T in $TABLES; do
      echo
      echo "### $SCHEMA.$T"
      OUT_DESC="$($Q --describe "$SCHEMA.$T" 2>&1)"
      if echo "$OUT_DESC" | grep -qiE "error|not exist|TrinoUserError"; then
        echo "_MISSING/ERROR: $(echo "$OUT_DESC" | head -1)_"
      else
        echo '```'
        echo "$OUT_DESC"
        echo '```'
      fi
    done
    echo
  done

  echo "## Freshness (max log_date / count)"
  echo '```'
  for ST in cfm_vn.std_ingame_user_active_daily cfm_vn.std_ingame_user_recharge_daily cfm_vn.etl_ingame_moneyflow cfm_vn.etl_ingame_game_detail cfm_vn.etl_ingame_login cros.std_ingame_user_active_daily tf.std_ingame_user_active_daily; do
    echo -n "$ST  "; $Q --maxdate "$ST" log_date 2>&1 | head -1
  done
  echo "-- role/map tables (no log_date → row counts) --"
  for ST in cfm_vn.mf_ingame_roles cfm_vn.map_ingame_devices_and_userid cfm_vn.map_ingame_ips_and_userid; do
    echo -n "$ST  "; $Q --sql "SELECT count(*) FROM $ST" 2>&1 | tail -1
  done
  echo '```'
} > "$OUT" 2>&1
echo "WROTE $OUT ($(wc -l < "$OUT") lines)"
